# more details this workflow and other at https://github.com/nholuongut/gcloud-tests
name: Use GCP filestore

on:

  workflow_dispatch:
    inputs: 
 
  push:
    #protection to avoid triggering when other workflow is modified
    paths: 
    - '!.github/workflows/**'
    - '.github/workflows/gcloud-filestore.yml'
    
  schedule:
    - cron:  '0 4 30 * MON' 

env:
  GCP_VERBOSITY: warning
  GCP_BUCKET: gs://test-gcp-bucket
  
jobs:
  use-GCP-filestore-services:
  
    runs-on: ubuntu-latest

    steps:
        
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Get gcloud version & info
      run: |-
        echo '--- gcloud version ---'
        gcloud version
        echo '--- gcloud info ---'
        gcloud info --anonymize
    
    # https://cloud.google.com/storage/docs/creating-buckets    
    - name: Create bucket
      run: |-
        gsutil mb -p ${{ secrets.GCP_PROJECT }} "$GCP_BUCKET-$GITHUB_SHA"
        
    - name: Copy file to bucket
      run: |-
        echo "content: $GITHUB_SHA" > "/tmp/file-$GITHUB_SHA.txt"
        gsutil cp  "/tmp/file-$GITHUB_SHA.txt" "$GCP_BUCKET-$GITHUB_SHA"
        
    - name: List bucket content
      run: |-
        gsutil ls -r "$GCP_BUCKET-$GITHUB_SHA/**"
        
        
    # diff is used to make sure that read content equals original one   
    - name: Read file from bucket (and diff to validate)
      run: |-
        gsutil cp "$GCP_BUCKET-$GITHUB_SHA/file-$GITHUB_SHA.txt" "/tmp/file-$GITHUB_SHA-read.txt"
        diff "/tmp/file-$GITHUB_SHA.txt" "/tmp/file-$GITHUB_SHA-read.txt"
        
    - name: Delete bucket
      run: |-
        gsutil rm -r "$GCP_BUCKET-$GITHUB_SHA"
        
    - name: List filestore buckets (to see if deleted)
      run: |-
        gsutil ls -p ${{ secrets.GCP_PROJECT }}
       
       